### ISSUE TITLE
yarn执行报错

### ISSUE THREAD

**Issue by whuhit** [ZhiShuYun/HubFrontend#19]
**Describe the bug**
你好，请教一下，执行yarn的时候，报错如下：
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

请问下执行这个yarn的时候是需要带参数，还是缺文件呢

**Comment by Germey** [comment]
@whuhit 看起来是 yarn 执行的不是 node 里面的 yarn，看看这个 issue 解决下：https://github.com/yarnpkg/yarn/issues/2821
